SQUARE_SIZE = 20
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
HUD_HEIGHT = 30
TILES_X = WINDOW_WIDTH // SQUARE_SIZE
TILES_Y = (WINDOW_HEIGHT - HUD_HEIGHT) // SQUARE_SIZE
LEVEL_CREATION_ITER = WINDOW_WIDTH * WINDOW_HEIGHT // (WINDOW_WIDTH + WINDOW_HEIGHT)
ALL_TILES_VISIBLE = False
DRAWING_FONT = ("Times New Roman", SQUARE_SIZE)
HEALTH_DECREASING = True
HEALTH_DECREASE_PER_TURN = ((max(round(25 / TILES_X, 2), round(25 / TILES_Y, 2))) / 2
                            if HEALTH_DECREASING else 0)
FOUNTAINS_PER_LEVEL = WINDOW_WIDTH // 400 + WINDOW_HEIGHT // 400  # some arbitrary number of objects
VISIBILITY_RANGE = 2
EXP_PER_LEVEL = 300
