#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="example")]
public partial class Example : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMiejscowosc(Miejscowosc instance);
  partial void UpdateMiejscowosc(Miejscowosc instance);
  partial void DeleteMiejscowosc(Miejscowosc instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  #endregion
	
	public Example(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Example(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Example(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Example(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Miejscowosc> Miejscowosc
	{
		get
		{
			return this.GetTable<Miejscowosc>();
		}
	}
	
	public System.Data.Linq.Table<Student> Student
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Miejscowosc")]
public partial class Miejscowosc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MiejscowoscId;
	
	private string _Nazwa;
	
	private EntitySet<Student> _Student;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMiejscowoscIdChanging(int value);
    partial void OnMiejscowoscIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
	
	public Miejscowosc()
	{
		this._Student = new EntitySet<Student>(new Action<Student>(this.attach_Student), new Action<Student>(this.detach_Student));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiejscowoscId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MiejscowoscId
	{
		get
		{
			return this._MiejscowoscId;
		}
		set
		{
			if ((this._MiejscowoscId != value))
			{
				this.OnMiejscowoscIdChanging(value);
				this.SendPropertyChanging();
				this._MiejscowoscId = value;
				this.SendPropertyChanged("MiejscowoscId");
				this.OnMiejscowoscIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Nazwa
	{
		get
		{
			return this._Nazwa;
		}
		set
		{
			if ((this._Nazwa != value))
			{
				this.OnNazwaChanging(value);
				this.SendPropertyChanging();
				this._Nazwa = value;
				this.SendPropertyChanged("Nazwa");
				this.OnNazwaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Student_Miejscowosc", Storage="_Student", ThisKey="MiejscowoscId", OtherKey="MiejscowoscId", DeleteRule="NO ACTION")]
	public EntitySet<Student> Student
	{
		get
		{
			return this._Student;
		}
		set
		{
			this._Student.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Student(Student entity)
	{
		this.SendPropertyChanging();
		entity.Miejscowosc = this;
	}
	
	private void detach_Student(Student entity)
	{
		this.SendPropertyChanging();
		entity.Miejscowosc = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _StudentId;
	
	private string _Imie;
	
	private string _Nazwisko;
	
	private System.DateTime _DataUrodzenia;
	
	private int _MiejscowoscId;
	
	private EntityRef<Miejscowosc> _Miejscowosc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIdChanging(int value);
    partial void OnStudentIdChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnDataUrodzeniaChanging(System.DateTime value);
    partial void OnDataUrodzeniaChanged();
    partial void OnMiejscowoscIdChanging(int value);
    partial void OnMiejscowoscIdChanged();
    #endregion
	
	public Student()
	{
		this._Miejscowosc = default(EntityRef<Miejscowosc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int StudentId
	{
		get
		{
			return this._StudentId;
		}
		set
		{
			if ((this._StudentId != value))
			{
				this.OnStudentIdChanging(value);
				this.SendPropertyChanging();
				this._StudentId = value;
				this.SendPropertyChanged("StudentId");
				this.OnStudentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Imie
	{
		get
		{
			return this._Imie;
		}
		set
		{
			if ((this._Imie != value))
			{
				this.OnImieChanging(value);
				this.SendPropertyChanging();
				this._Imie = value;
				this.SendPropertyChanged("Imie");
				this.OnImieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Nazwisko
	{
		get
		{
			return this._Nazwisko;
		}
		set
		{
			if ((this._Nazwisko != value))
			{
				this.OnNazwiskoChanging(value);
				this.SendPropertyChanging();
				this._Nazwisko = value;
				this.SendPropertyChanged("Nazwisko");
				this.OnNazwiskoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataUrodzenia", DbType="Date NOT NULL")]
	public System.DateTime DataUrodzenia
	{
		get
		{
			return this._DataUrodzenia;
		}
		set
		{
			if ((this._DataUrodzenia != value))
			{
				this.OnDataUrodzeniaChanging(value);
				this.SendPropertyChanging();
				this._DataUrodzenia = value;
				this.SendPropertyChanged("DataUrodzenia");
				this.OnDataUrodzeniaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiejscowoscId", DbType="Int NOT NULL")]
	public int MiejscowoscId
	{
		get
		{
			return this._MiejscowoscId;
		}
		set
		{
			if ((this._MiejscowoscId != value))
			{
				if (this._Miejscowosc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMiejscowoscIdChanging(value);
				this.SendPropertyChanging();
				this._MiejscowoscId = value;
				this.SendPropertyChanged("MiejscowoscId");
				this.OnMiejscowoscIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Student_Miejscowosc", Storage="_Miejscowosc", ThisKey="MiejscowoscId", OtherKey="MiejscowoscId", IsForeignKey=true)]
	public Miejscowosc Miejscowosc
	{
		get
		{
			return this._Miejscowosc.Entity;
		}
		set
		{
			Miejscowosc previousValue = this._Miejscowosc.Entity;
			if (((previousValue != value) 
						|| (this._Miejscowosc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Miejscowosc.Entity = null;
					previousValue.Student.Remove(this);
				}
				this._Miejscowosc.Entity = value;
				if ((value != null))
				{
					value.Student.Add(this);
					this._MiejscowoscId = value.MiejscowoscId;
				}
				else
				{
					this._MiejscowoscId = default(int);
				}
				this.SendPropertyChanged("Miejscowosc");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
